### ISSUE TITLE
TickTick Backup Files aren't Recognized

### ISSUE THREAD

**Issue by csatwood** [mrzmyr/ticktick-to-todoist#1]
When uploading a fresh TickTick Backup file into the tool it throws an error stating that "Invalid CSV file, please provide a tick tick backup file", I've tried in Safari and Chrome and with a few backup files as well and haven't had change in behavior.

**Comment by mrzmyr** [comment]
Hi @csatwood, seems like your header columns in your backup are not the same as expected: https://github.com/mrzmyr/ticktick-to-todoist/blob/9cc7c7962aca6ed32b41b93f58a14dd61c35c871/pages/index.js#L71

Did you check on that?

**Comment by csatwood** [comment]
I didn't change anything, the file is just as it came from TickTick when I exported it. Is there some change or clean-up that I need to do before uploading the file?

**Comment by mrzmyr** [comment]
Can you try if it works with this one: https://ticktick-to-todoist-evwzhzjx3-mrzmyr.vercel.app?

**Comment by csatwood** [comment]
That looks to have done the trick! It works as expected now. Did something change in the backup or was it something in the way that I had my headers setup? I wasn't doing anything odd from what TickTick supports.

**Comment by mrzmyr** [comment]
Perfect, yes a new key was added from the side of TickTick to the backup file. Thanks for pointing that out.
